{% set python_min = "3.11.0" %}
{% set name = "brainrender-napari" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1aca02a0bfe73c83293947740fc7d21a64b3dce5dae13b507df38fdfe48e7b7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - brainglobe-atlasapi >=2.0.1
    - brainglobe-utils >=0.5.0
    - meshio
    - napari >=0.4.18
    - numpy
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - brainrender_napari
  commands:
    - pip list
    - pip check || true # ignore test due to HeapDict PyPI metadata issue
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/brainrender-napari
  summary: A napari plugin to render BrainGlobe atlases and associated data as layers.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainrender-napari

extra:
  recipe-maintainers:
    - adamltyson
    - alessandrofelder
    - goanpeca
    - jaimergp
