{% set name = "brainrender-napari" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainrender-napari-{{ version }}.tar.gz
  sha256: 2ebfc21509ea5b73dcb6578414ae61188418be02864e0a2155d460ad70b42085

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9.0
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - brainglobe-atlasapi >=2.0.1
    - brainglobe-utils >= 0.5.0
    - meshio
    - napari >=0.4.18
    - numpy
    - python >=3.9.0
    - qtpy

test:
  imports:
    - brainrender_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/brainrender-napari
  summary: A napari plugin to render BrainGlobe atlases and associated data as layers.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainrender-napari

extra:
  recipe-maintainers:
    - adamltyson
    - alessandrofelder
    - goanpeca
    - jaimergp
